### ISSUE TITLE
debian.sh fails

### ISSUE THREAD

**Issue by nilsjha** [mpbraendli/mmbtools-aux#1]
The debian.sh script fails on Debian Jessie (8.4.0) x64 when configuring ODR-DabMux after compilation. It seems to fail to configure cURL. The error occurs when running the script at both of my Debian instances. Thanks in advance for any help that might resolve this issue.

Extract from ssh connection to server:

**Linking CXX executable etisnoop**
[100%] Built target etisnoop
[100%] Built target etisnoop
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/etisnoop
-- Removed runtime path from "/usr/local/bin/etisnoop"
~/sdr-dab/mmbtools-aux/installer/dab
** Compiling ODR-DabMux**
Cloning into 'ODR-DabMux'...
remote: Counting objects: 2701, done.
remote: Total 2701 (delta 0), reused 0 (delta 0), pack-reused 2701
Receiving objects: 100% (2701/2701), 1.69 MiB | 336.00 KiB/s, done.
Resolving deltas: 100% (2047/2047), done.
Checking connectivity... done.
~/sdr-dab/mmbtools-aux/installer/dab/ODR-DabMux ~/sdr-dab/mmbtools-aux/installer/dab
configure.ac:51: installing 'build-aux/compile'
configure.ac:22: installing 'build-aux/config.guess'
configure.ac:22: installing 'build-aux/config.sub'
configure.ac:23: installing 'build-aux/install-sh'
configure.ac:23: installing 'build-aux/missing'
src/Makefile.am: installing 'build-aux/depcomp'
You can call ./configure now
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking for pthread_create in -lpthread... yes
checking for boostlib >= 1.48.0... yes
checking for sin in -lm... yes
checking for library containing init_rs_char... -lfec
checking for OS type... checking how to run the C preprocessor... gcc -E
linux
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for ssize_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for working volatile... yes
checking whether gcc needs -traditional... no
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking return type of signal handlers... void
checking for vprintf... yes
checking for _doprnt... no
checking for bzero... yes
checking for gethostbyname... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for socket... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for zmq_init in -lzmq... yes
checking for zmq_init in -lzmq... (cached) yes
checking for curl_easy_init in -lcurl... no
configure: error: cURL is required for EDI output
user@dab-mod:~/sdr-dab/mmbtools-aux/installer$

**Comment by mpbraendli** [comment]
The curl dependency was indeed missing. Thanks, commit d0f0ca7 should fix this.
