### ISSUE TITLE
gnuradio-livecd.sh not working

### ISSUE THREAD

**Issue by gerritkramer** [mpbraendli/mmbtools-aux#2]
gnuradio-livecd.sh
ubuntu@ubuntu:~/Downloads$ ./gnuradio-livecd.sh
./gnuradio-livecd.sh: line 5: syntax error near unexpected token `newline'
./gnuradio-livecd.sh: line 5: `<!DOCTYPE html>'

The file is executable (chmod +x)
I work with latest version of Gnuradio 3.7.10 on usb.

I'm doing something wrong?

**Comment by mpbraendli** [comment]
Hi, I suspect you downloaded the html page, and not the script. Press the "raw" button, it will lead you to https://raw.githubusercontent.com/mpbraendli/mmbtools-aux/master/installer/gnuradio-livecd.sh

**Comment by gerritkramer** [comment]
Indeed that was the solution. I'm only a beginner with Ubuntu, so I must learn.

Thank you very much!
