### ISSUE TITLE
debian.sh fails on etisnoop

### ISSUE THREAD

**Issue by wnelis** [mpbraendli/mmbtools-aux#3]
Output on screen when running script debian.sh:

 Fetching etisnoop 
Cloning into 'etisnoop'...
remote: Counting objects: 446, done.
remote: Total 446 (delta 0), reused 0 (delta 0), pack-reused 446
Receiving objects: 100% (446/446), 302.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (277/277), done.
Checking connectivity... done.
~/dab/etisnoop ~/dab
CMake Error: The source directory "/home/dabplus/dab/etisnoop" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

The following snippet of script debian.sh:

echo -e "$GREEN Fetching etisnoop $NORMAL"
git clone https://github.com/Opendigitalradio/etisnoop.git
pushd etisnoop
mkdir build
cd build
cmake ..
make
sudo make install
popd

is replaced by:

echo -e "$GREEN Fetching etisnoop $NORMAL"
git clone https://github.com/Opendigitalradio/etisnoop.git
pushd etisnoop
./bootstrap.sh
./configure
make
sudo make install
popd

This seems to solve the issue.

**Comment by mpbraendli** [comment]
Hi, good observation. a6f7432e0 should fix this.
