### ISSUE TITLE
show_dabmux_stats not showing graphs

### ISSUE THREAD

**Issue by mrdj2** [mpbraendli/mmbtools-aux#4]
Hello,

I tried to use show_dabmux_stats.py on my Munin runinig on debian 8 Jesse, but no luck with the graphs.
This plugin is not visible on Munin www intreface

But, If i run it on munin-run I get correct output. I get it also with telnet fetch. 
Other Munin graphs are working correctly, so Munin is correctly installed.

What could be the problem?

Thanks and br, David

**Comment by mrdj2** [comment]
I thik i found problem. 

Here si debuging:
2017/07/17 23:08:56 [FETCH from show_dabmux_stats_py] id                       max     min   under    over  peak L  peak R
2017/07/17 23:08:56 [DEBUG] Protocol exception while fetching 'show_dabmux_stats_py' from show_dabmux_stats_py on dab3/127.0.0.1:4949: unrecognized line 'id                       max     min   under    over  peak L  peak R'

And than here:
2017/07/17 23:08:56 [DEBUG] munin_set_var_path: Setting var "dab3;dab3:show_dabmux_stats_py._u_sub_s1__" = "u'sub-s2', u'sub-s3', u'sub-s4', u'sub-s5', u'sub-s6', u'sub-s7', u'sub-s8']"
2017/07/17 23:08:56 [WARNING] munin_set_var_loc: Setting unknown option '_u_sub_s1__' at dab3;dab3;show_dabmux_stats_py:

It sems that first service in mux is not correctly recoginzed...?

Thanks and br, David

**Comment by mpbraendli** [comment]
Hi,
the comment in the file seems to be misleading. If you want to connect to munin, use
https://github.com/Opendigitalradio/ODR-DabMux/blob/master/doc/stats_dabmux_multi.py

the show_dabmux_stats script prints it to standard output so that you can check the stats, it's not for munin.

I'll fix the comment in the file.

**Comment by mrdj2** [comment]
Hi,

 

Thank you very much.

 

That cleras the confusion - now it works. J

 

Br, David
