### ISSUE TITLE
Trouble compile zmq-sub.c under Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by chris1350** [mpbraendli/mmbtools-aux#5]
Hello,

I'm not able to compile zmq-sub.c under Ubuntu 16.04 LTS because of the following error:

$ make zmq-sub
gcc -Wall -g -std=gnu11 -lzmq -DGIT_VERSION=\"g7959f2c\" -o zmq-sub zmq-sub.c
/tmp/ccHjvPw8.o: In function `barf':
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:41: undefined reference to `zmq_strerror'
/tmp/ccHjvPw8.o: In function `do_subscriber':
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:50: undefined reference to `zmq_ctx_new'
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:51: undefined reference to `zmq_socket'
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:56: undefined reference to `zmq_connect'
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:60: undefined reference to `zmq_setsockopt'
/home/user/mmbtools-aux/zmqtest/zmq-sub/zmq-sub.c:79: undefined reference to `zmq_recv'
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'zmq-sub' failed
make: *** [zmq-sub] Error 1

My zmq libs are:
dpkg -l | grep libzmq
ii  libzmq3-dev:amd64                           4.1.4-7                                                                     amd64        lightweight messaging kernel (development files)
ii  libzmq5:amd64                               4.1.4-7                                                                     amd64        lightweight messaging kernel (shared library)

I also tried different libzmq with the same result.
I also compiled zmq-sub successfully under other distro without any problems.

Please help.
Thanks Chris

**Comment by mpbraendli** [comment]
What's the output of `pkg-config --libs libzmq` on your machine? Maybe ubuntu gives the library another name...

**Comment by mpbraendli** [comment]
I've added a small check to the makefile, maybe it works now.

**Comment by chris1350** [comment]
$ pkg-config --libs libzmq
-lzmq

But I still have the issue after getting the new version with the check.
I solved the issue by passing the lib to gcc at the end of the line:
gcc -Wall -g -std=gnu11 -DGIT_VERSION=\"gaeaa5ab\" -o zmq-sub zmq-sub.c -l zmq

Now works like a charm !
Dumping ETI stream thru a L2TP/IPSEC tunnel :-)

Thanks
Chris

**Comment by mpbraendli** [comment]
Ok, I've modified the Makefile again and put it at the end. I've also clarified under what licence (MIT) the `zmq-sub.c` file is distributed.
Thank you for the bugreport!
Out of curiosity, what are you doing with the ETI file? Analysis? Monitoring?

**Comment by chris1350** [comment]
I'm interested to see how the synchronization and time stamping is made and currently checking the traffic in Wireshark

**Comment by mpbraendli** [comment]
Ok, regarding timestamping, keep in mind ETI usually only includes a timestamp that has a second ambiguity (the TIST). In ODR-DabMux, I've added absolute time in the MNSC, which can be combined with TIST to calculate an absolute timestamp.
If you have any question feel free to ask (rather by email than using this issue)
