### ISSUE TITLE
ZMQ ETI Sender

### ISSUE THREAD

**Issue by lars18th** [mpbraendli/mmbtools-aux#6]
Hi @mpbraendli ,

I hope this sounds good to you: The tool "ZMQ ETI Receiver" it's great. However, in other to increment the interoperatibility with other tools, a similiar tool like "ZMQ ETI Sender" will be desirable. This tool will do the same in reverse: it reads ETI-NI frames of 6144 bytes in length  from the STDIN and sends them over a ZeroMQ output.

What you think?

**Comment by mpbraendli** [comment]
Hi @lars18th 

It can be useful indeed, but I don't have time to implement it and I don't have any use for such a tool myself. I'm afraid this proposal won't be high enough on my todo list to ever get done.

Sorry.
