### ISSUE TITLE
uecp_parse question

### ISSUE THREAD

**Issue by veso266** [mpbraendli/mmbtools-aux#7]
Hi I was wondering if your https://github.com/mpbraendli/mmbtools-aux/blob/master/uecpparse/uecp_parse.py can read raw uecp data generated with something like: https://github.com/Palakis/uecp-sharp

because I can't realy understand the line: 
```
# A UECP decoder, reading from a UDP socket, receiving
# data generated by my patched VLC, from ancillary MP2 bytes in a MPEG-TS
#
```
is this UECP or mpeg-ts stream that uecp_parse.py reads

cause when I try to use it (I had to change UDP_IP to '' because otherwise no data would come through)
I get 
```
ValueError: invalid literal for int() with base 10: '\xfe'
```
on this line
```
line_bytes = [int(i) for i in data]
```

Thanks for Anwsering and Best Regards

**Comment by mpbraendli** [comment]
I had a scenario where MP2 was carried in an MPEG-TS. That MP2 contained ancillary bytes, which was this UECP I was interested in.
I patched VLC to output the ancillary bytes over UDP. This script receives UECP.

Regarding your error, I suspect this might only work in python2.
Try with
`line_bytes = list(data)`
instead.

**Comment by veso266** [comment]
Thanks for helping but it still fails now on a 
```
anc_bytes = line_bytes[1:1+anc_len]

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

I am trying this on python2.7 not sure why it wouldn't work in it

**Comment by mpbraendli** [comment]
I'm afraid you will have to do some debugging :-/ I cannot test this easily, I don't have a UECP source ready.

**Comment by veso266** [comment]
you could compile this one: https://github.com/UoC-Radio/rds-control
